
AAs = [
    "ALA",
    "ARG",
    "ASN",
    "ASP",
    "CYS",
    "GLN",
    "GLU",
    "GLY",
    "HIS",
    "ILE",
    "LEU",
    "LYS",
    "MET",
    "PHE",
    "PRO",
    "SER",
    "THR",
    "TRP",
    "TYR",
    "VAL",
]

AA_REF = {
    "GLY": 0,
    "PRO": 1,
    "ASP": 2,
    "GLU": 3,
    "LYS": 4,
    "ARG": 5,
    "HIS": 6,
    "SER": 7,
    "THR": 8,
    "ASN": 9,
    "GLN": 10,
    "ALA": 11,
    "MET": 12,
    "TYR": 13,
    "TRP": 14,
    "VAL": 15,
    "ILE": 16,
    "LEU": 17,
    "PHE": 18,
    "CYS": 19,
}

L_MAP = {
            "ALL": [1, 2, 3, 4, 5, 6],
            "WATER": [1, 6],
            "INTERFACE": [2, 5],
            "HYDROPHOBIC": [3, 4],
            "W_IN":  [1],
            "I_IN":  [2],
            "H_IN":  [3],
            "H_OUT": [4],
            "I_OUT": [5],
            "W_OUT": [6],
}
